import { Language } from './types';

export const FIREBASE_CONFIG = {
  apiKey: "AIzaSyBCWVsaEY9xgPM6XtpdlJ0WAJXgqLQtyMA",
  authDomain: "ai-firebase-app-test.firebaseapp.com",
  databaseURL: "https://ai-firebase-app-test-default-rtdb.firebaseio.com",
  projectId: "ai-firebase-app-test",
  storageBucket: "ai-firebase-app-test.firebasestorage.app",
  messagingSenderId: "554156934922",
  appId: "1:554156934922:web:fae783ce2d35d700e8dcf3",
  measurementId: "G-776JQ5NT9Z"
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    dashboard: "Dashboard",
    customers: "Customers",
    sales: "Sales",
    payments: "Payments",
    reports: "Reports",
    settings: "Settings",
    logout: "Logout",
    totalCustomers: "Total Customers",
    totalSales: "Total Sales",
    totalCollection: "Total Collection",
    totalDue: "Total Due",
    activeInstallments: "Active Installments",
    completedInstallments: "Completed Installments",
    todaysCollection: "Today's Collection",
    addCustomer: "Add Customer",
    search: "Search...",
    name: "Name",
    phone: "Phone",
    actions: "Actions",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    invoice: "Invoice",
    date: "Date",
    brand: "Brand",
    model: "Model",
    price: "Price",
    downPayment: "Down Payment",
    months: "Months",
    addSale: "New Sale",
    addPayment: "Add Payment",
    amount: "Amount",
    status: "Status",
    paid: "Paid",
    due: "Due",
    overdue: "Overdue",
    upcoming: "Upcoming",
    partial: "Partial",
    print: "Print",
    share: "Share",
    language: "Language",
    theme: "Theme",
    dark: "Dark",
    light: "Light",
    english: "English",
    bengali: "Bengali",
  },
  bn: {
    dashboard: "ড্যাশবোর্ড",
    customers: "গ্রাহক",
    sales: "বিক্রয়",
    payments: "পেমেন্ট",
    reports: "রিপোর্ট",
    settings: "সেটিংস",
    logout: "লগআউট",
    totalCustomers: "মোট গ্রাহক",
    totalSales: "মোট বিক্রয়",
    totalCollection: "মোট সংগ্রহ",
    totalDue: "মোট বকেয়া",
    activeInstallments: "চলমান কিস্তি",
    completedInstallments: "সম্পন্ন কিস্তি",
    todaysCollection: "আজকের সংগ্রহ",
    addCustomer: "গ্রাহক যোগ করুন",
    search: "অনুসন্ধান...",
    name: "নাম",
    phone: "ফোন",
    actions: "অ্যাকশন",
    save: "সংরক্ষণ করুন",
    cancel: "বাতিল",
    edit: "সম্পাদনা",
    delete: "মুছে ফেলুন",
    invoice: "ইনভয়েস",
    date: "তারিখ",
    brand: "ব্র্যান্ড",
    model: "মডেল",
    price: "মূল্য",
    downPayment: "ডাউন পেমেন্ট",
    months: "মাস",
    addSale: "নতুন বিক্রয়",
    addPayment: "পেমেন্ট যোগ করুন",
    amount: "পরিমাণ",
    status: "স্ট্যাটাস",
    paid: "পরিশোধিত",
    due: "বকেয়া",
    overdue: "মেয়াদোত্তীর্ণ",
    upcoming: "আসন্ন",
    partial: "আংশিক",
    print: "প্রিন্ট",
    share: "শেয়ার",
    language: "ভাষা",
    theme: "থিম",
    dark: "ডার্ক",
    light: "লাইট",
    english: "ইংরেজি",
    bengali: "বাংলা",
  }
};
